name: Suspend Render Scanner

on:
  schedule:
    - cron: "20 20 * * 1-5"
  workflow_dispatch:

jobs:
  suspend:
    runs-on: ubuntu-latest

    steps:
      - name: Suspend service
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/suspend" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
